import Image from "next/image";
import Link from "next/link";

import dynamic from "next/dynamic";

const Marquee = dynamic(() => import("@/components/kibo-ui/marquee").then(mod => mod.Marquee), { ssr: true });
const MarqueeContent = dynamic(() => import("@/components/kibo-ui/marquee").then(mod => mod.MarqueeContent), { ssr: true });
const MarqueeFade = dynamic(() => import("@/components/kibo-ui/marquee").then(mod => mod.MarqueeFade), { ssr: true });
const MarqueeItem = dynamic(() => import("@/components/kibo-ui/marquee").then(mod => mod.MarqueeItem), { ssr: true });

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const achievements = [
  { label: "Years of Academic Experience", value: "20+" },
  { label: "Assignments Completed", value: "15K+" },
  { label: "Student Satisfaction", value: "99%" },
  { label: "Professional Academic Writers", value: "100+" },
];

const trustedSubjects = [
  "Math Homework Help",
  "Accounting Homework Help",
  "Nursing Assignments",
  "Essay Writing Services",
  "Research Paper Writing",
  "Online Class Help",
  "Statistics Homework Help",
  "Business Assignments",
];

const contentSections = [
  {
    title: "Experienced Academic Professionals",
    content:
      "Homework Helpers LA has supported college and university students for more than 20 years with professional academic assistance. Our team includes experienced academic writers, researchers, tutors, and subject specialists dedicated to helping students succeed.\n\nWe provide high-quality homework help, essay writing, research paper support, and online class assistance across a wide range of academic subjects including nursing, business, accounting, statistics, science, and mathematics.\n\nEvery assignment is completed carefully, professionally, and tailored to your specific course requirements.",
  },

  {
    title: "Original, Human-Written Academic Work",
    content:
      "We believe students deserve authentic academic support from real professionals. Every paper and assignment is written by seasoned academic experts — never generated by AI tools.\n\nOur work is plagiarism-free, properly researched, and carefully formatted to meet university standards. We focus on quality, accuracy, confidentiality, and timely delivery for every student we assist.\n\nWhether you need urgent homework help or long-term academic support, Homework Helpers LA is committed to helping you achieve better academic results with confidence.",
  },
];

const About3 = ({ className }: { className?: string }) => {
  return (
    <section
      className={cn(
        "relative overflow-hidden py-24 border-b",
        className
      )}
    >
      <div className="container">
        {/* Header */}
        <div className="mx-auto mb-16 text-center">
          <span className="inline-flex rounded-full bg-accent/10 px-4 py-1 text-sm font-semibold text-accent">
            About Us
          </span>

          <h2 className="mx-auto mt-6 max-w-5xl text-4xl lg:text-5xl font-black text-primary leading-[1.2]">
            LA&rsquo;s Most Trusted <span className="text-accent">Homework Helpers</span> for College Students
          </h2>

          <p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-muted-foreground ">
            Homework Helpers LA provides professional homework help,
            essay writing, research paper assistance, and online class
            support for college and university students across Los Angeles.
            With over 20 years of academic experience, our team delivers
            original, plagiarism-free work written by real academic experts
            — never AI-generated content.
          </p>
        </div>

        {/* Images + Feature Card */}
        <div className="grid gap-7 lg:grid-cols-3">
          {/* Main Image */}
          <div className="relative overflow-hidden rounded-3xl lg:col-span-2">
            <Image
              src="/about-main.webp"
              alt="Professional homework help and essay writing services in Los Angeles"
              width={800}
              height={600}
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 66vw, 800px"
              className="h-full min-h-[420px] w-full object-cover"
            />
          </div>

          {/* Side Content */}
          <div className="flex flex-col gap-7">
            {/* Feature Card */}
            <div className="flex flex-col justify-between rounded-3xl border bg-card p-8 shadow-sm">
              <div>
                <div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-primary">
                  <span className="text-lg font-black text-white">
                    LA
                  </span>
                </div>

                <h3 className="text-2xl font-bold text-primary">
                  Professional Academic Homework Help
                </h3>

                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Our experienced academic writers and homework experts
                  help students complete assignments accurately, on time,
                  and according to university standards.
                </p>
              </div>

              <div className="mt-8 space-y-3">
                <div className="flex items-center gap-2 text-sm font-medium">
                  <div className="size-2 rounded-full bg-accent" />
                  100% Human-Written Work
                </div>

                <div className="flex items-center gap-2 text-sm font-medium">
                  <div className="size-2 rounded-full bg-accent" />
                  Plagiarism-Free Assignments
                </div>

                <div className="flex items-center gap-2 text-sm font-medium">
                  <div className="size-2 rounded-full bg-accent" />
                  24/7 Homework Support
                </div>
              </div>

              <Button
                asChild
                className="mt-8 bg-accent text-accent-foreground hover:opacity-90"
              >
                <Link href="/order-now" prefetch={false}>
                  Get Homework Help
                </Link>
              </Button>
            </div>

            {/* Secondary Image */}
            <div className="relative overflow-hidden rounded-3xl">
              <Image
                src="/about-secondary.webp"
                alt="College students receiving academic support"
                width={700}
                height={500}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 33vw, 400px"
                className="h-full min-h-[260px] w-full object-cover"
              />
            </div>
          </div>
        </div>

        {/* Subjects Marquee */}
        <div className="py-24">
          <Marquee>
            <MarqueeContent speed={40}>
              {trustedSubjects.map((subject, idx) => (
                <MarqueeItem
                  key={subject + idx}
                  className="mx-4"
                >
                  <div className="rounded-2xl border bg-card px-6 py-4 text-sm font-semibold shadow-sm">
                    {subject}
                  </div>
                </MarqueeItem>
              ))}
            </MarqueeContent>

            <MarqueeFade side="left" />
            <MarqueeFade side="right" />
          </Marquee>
        </div>

        {/* Achievements */}
        <div className="relative overflow-hidden rounded-3xl border bg-accent/20 p-8 md:p-14">
          <div className="max-w-2xl">
            <h3 className="text-3xl font-bold text-primary md:text-4xl">
              Over Two Decades of Academic Excellence
            </h3>

            <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
              We have helped thousands of students across Los Angeles
              and beyond with reliable, confidential, and professional
              academic support services.
            </p>
          </div>

          <div className="mt-14 grid grid-cols-2 gap-8 lg:grid-cols-4">
            {achievements.map((item, idx) => (
              <div key={item.label + idx}>
                <div className="text-4xl font-black text-primary md:text-5xl">
                  {item.value}
                </div>

                <p className="mt-3 text-sm font-medium text-muted-foreground">
                  {item.label}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Content Sections */}
        <div className="mx-auto grid max-w-6xl gap-14 py-24 lg:grid-cols-2 lg:gap-20 ">
          {contentSections.map((section, idx) => (
            <div key={section.title + idx} className="border p-8 rounded-xl">
              <h3 className="text-2xl font-bold mb-6 mt-6 tracking-tight text-primary">
                {section.title}
              </h3>

              <p className="whitespace-pre-line leading-8 text-muted-foreground">
                {section.content}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export { About3 };